### PR TITLE
Wysiwyg round2 sy

### PR DESCRIPTION
**Pull request by Sanyyouisf**

### CODE REVIEW

**Comment by Sanyyouisf** [comment]
@ostrander-nathan
some notes like to add them with your help 
 1- when writing in the text input  i like to add  data to the bio section ,not replace it .
 2- when press enter in the text box , put the old bio back to the card .

**Comment by Sanyyouisf** [comment]
@drdreed
finish

**Comment by DevDreed** [comment]
👍 Looks good.  We fixed the issues during our meeting.

**Comment by Sanyyouisf** [comment]
@drdreed
thanks

**Pull request merged**
